from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class ActivityShikigamiAssets: 


	# Click Rule Assets
	# description 
	C_RANDOM_LEFT = RuleClick(roi_front=(17,84,104,356), roi_back=(17,81,106,365), name="random_left")
	# description 
	C_RANDOM_RIGHT = RuleClick(roi_front=(1133,88,131,361), roi_back=(1131,84,133,363), name="random_right")
	# description 
	C_RANDOM_TOP = RuleClick(roi_front=(126,66,989,58), roi_back=(123,65,991,58), name="random_top")
	# description 
	C_RANDOM_BOTTOM = RuleClick(roi_front=(196,598,581,78), roi_back=(194,597,583,81), name="random_bottom")
	# description 
	C_RANDOM_ALL = RuleClick(roi_front=(42,94,1207,543), roi_back=(42,94,1207,543), name="random_all")


	# Image Rule Assets
	# 上锁图标 
	I_LOCK = RuleImage(roi_front=(782,652,28,25), roi_back=(739,613,276,85), threshold=0.5, method="Template matching", file="./tasks/ActivityShikigami/as/as_lock.png")
	# 还未上锁图片 
	I_UNLOCK = RuleImage(roi_front=(779,649,28,25), roi_back=(733,607,266,95), threshold=0.5, method="Template matching", file="./tasks/ActivityShikigami/as/as_unlock.png")
	# 活动爬塔标志 
	I_CLIMB_MODE_PASS = RuleImage(roi_front=(1138,540,30,34), roi_back=(1118,510,70,69), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_pass.png")
	# 体力爬塔标志 
	I_CLIMB_MODE_AP = RuleImage(roi_front=(1090,545,22,25), roi_back=(1055,495,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_ap.png")
	# 切换按键 
	I_CLIMB_MODE_SWITCH = RuleImage(roi_front=(1232,544,29,26), roi_back=(1174,511,104,82), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_climb_mode_switch.png")


	# Image Rule Assets
	# 庭院进入活动入口 
	I_SHI = RuleImage(roi_front=(1193,381,31,35), roi_back=(1155,115,98,473), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_shi.png")
	# 左上角返回 
	I_BACK_GREEN = RuleImage(roi_front=(27,19,34,38), roi_back=(2,1,170,75), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_back_green.png")
	# 右上跳过按钮 
	I_SKIP_BUTTON = RuleImage(roi_front=(1159,37,51,22), roi_back=(1141,27,86,43), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_skip_button.png")
	# 红色退出 
	I_RED_EXIT = RuleImage(roi_front=(1162,96,39,38), roi_back=(1120,49,110,135), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_red_exit.png")
	# 进入当前活动爬塔战斗界面 
	I_TO_BATTLE_MAIN = RuleImage(roi_front=(603,412,28,122), roi_back=(593,397,50,169), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_as_check_battle_boss.png")
	# 点击进入boss战斗页面 
	I_TO_BATTLE_BOSS = RuleImage(roi_front=(1085,289,33,121), roi_back=(934,209,234,327), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_to_battle_boss.png")
	# description 
	I_CHECK_BATTLE_MAIN = RuleImage(roi_front=(1136,596,90,62), roi_back=(1095,570,175,135), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_check_battle_main.png")
	# description 
	I_CHECK_BATTLE_BOSS = RuleImage(roi_front=(34,365,45,35), roi_back=(20,328,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_check_battle_boss.png")
	# 从main进入到式神录 
	I_BATTLE_MAIN_TO_RECORDS = RuleImage(roi_front=(1017,564,35,38), roi_back=(966,534,140,100), threshold=0.7, method="Template matching", file="./tasks/ActivityShikigami/as/as_battle_main_to_records.png")
	# description 
	I_TO_BATTLE_MAIN_2 = RuleImage(roi_front=(15,94,247,38), roi_back=(2,68,311,100), threshold=0.65, method="Template matching", file="./tasks/ActivityShikigami/as/as_to_battle_main_2.png")
	# 确认跳过 
	I_CONFIRM_SKIP = RuleImage(roi_front=(707,442,137,38), roi_back=(656,397,231,124), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_confirm_skip.png")
	# 每日奖励弹窗 
	I_DAYLY_REWARD = RuleImage(roi_front=(477,246,106,34), roi_back=(464,229,140,77), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_dayly_reward.png")
	# 红色退出2，每日补给关闭界面 
	I_RED_EXIT2 = RuleImage(roi_front=(1106,190,29,27), roi_back=(1061,152,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/as/as_red_exit2.png")


	# Image Rule Assets
	# 战斗页挑战按钮 
	I_FIRE_BUTTON = RuleImage(roi_front=(1136,596,90,62), roi_back=(1095,570,175,135), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_fire_button.png")
	# description 
	I_PASS_1 = RuleImage(roi_front=(359,295,100,53), roi_back=(68,203,1138,369), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_1.png")
	# description 
	I_PASS_2 = RuleImage(roi_front=(645,224,92,57), roi_back=(98,205,1076,366), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_2.png")
	# description 
	I_PASS_3 = RuleImage(roi_front=(648,227,91,55), roi_back=(103,162,1077,416), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_3.png")
	# description 
	I_PASS_4 = RuleImage(roi_front=(586,424,100,58), roi_back=(99,194,1080,398), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_4.png")
	# 箱子 
	I_PASS_5 = RuleImage(roi_front=(946,415,65,48), roi_back=(97,194,1036,398), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_5.png")
	# 印记 
	I_PASS_6 = RuleImage(roi_front=(668,221,54,50), roi_back=(107,159,1012,394), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_6.png")
	# description 
	I_PASS_7 = RuleImage(roi_front=(329,233,51,51), roi_back=(95,180,1056,394), threshold=0.65, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_7.png")
	# 印记选中间的 
	I_PASS_8 = RuleImage(roi_front=(579,276,100,100), roi_back=(577,296,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_8.png")
	# description 
	I_PASS_9 = RuleImage(roi_front=(558,643,160,44), roi_back=(480,601,306,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_9.png")
	# 印记选左边的 
	I_PASS_10 = RuleImage(roi_front=(279,309,100,100), roi_back=(291,305,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_10.png")
	# 印记选右边的 
	I_PASS_11 = RuleImage(roi_front=(918,304,100,100), roi_back=(914,308,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_11.png")
	# 击败魇兽将直接前往下一层 
	I_PASS12 = RuleImage(roi_front=(870,356,100,50), roi_back=(104,169,1109,425), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass12.png")
	# 魇兽将的战斗图片 
	I_PASS_13 = RuleImage(roi_front=(1018,570,100,100), roi_back=(984,538,169,152), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_pass_13.png")
	# 战斗准备界面的式神录入口 
	I_SHISHENLU = RuleImage(roi_front=(997,559,45,46), roi_back=(964,533,100,100), threshold=0.8, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_shishenlu.png")
	# 5倍挑战开启 
	I_TIMESX5_TRUE = RuleImage(roi_front=(845,646,44,47), roi_back=(832,628,69,80), threshold=0.9, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_timesx5_ture.png")
	# 5倍挑战关闭 
	I_TIMESX5_FALSE = RuleImage(roi_front=(840,642,52,50), roi_back=(814,619,100,100), threshold=0.9, method="Template matching", file="./tasks/ActivityShikigami/fire/fire_timesx5_false.png")


	# Ocr Rule Assets
	# 挑战 
	O_FIRE = RuleOcr(roi=(1124,599,96,50), area=(1123,570,106,100), mode="Single", method="Default", keyword="挑战", name="fire")
	# 体力的数量检测 
	O_REMAIN_AP = RuleOcr(roi=(1126,23,90,33), area=(1106,23,134,33), mode="Quantity", method="Default", keyword="", name="remain_ap")
	# 活动体力的剩余检测 
	O_REMAIN_PASS = RuleOcr(roi=(540,26,77,27), area=(1043,177,92,20), mode="DigitSmall", method="Default", keyword="", name="remain_pass")
	# 还有多少次购买体力的机会 
	O_REMAIN_BUY = RuleOcr(roi=(808,531,39,42), area=(808,531,39,42), mode="DigitCounter", method="Default", keyword="", name="remain_buy")
	# 活动票数（没有百分比） 
	O_REMAIN_PASS2 = RuleOcr(roi=(731,25,76,27), area=(629,97,77,38), mode="Digit", method="Default", keyword="", name="remain_pass2")
	# boss剩余攻击次数 
	O_REMAIN_BOSS = RuleOcr(roi=(1113,669,131,31), area=(1099,659,162,52), mode="DigitCounter", method="Default", keyword="", name="remain_boss")
	# 100体活动门票检测 
	O_REMAIN_AP100 = RuleOcr(roi=(927,28,100,25), area=(906,22,125,36), mode="Digit", method="Default", keyword="", name="remain_ap100")
	# 进入100体活动标识 
	O_ENTER_AP100 = RuleOcr(roi=(73,98,95,32), area=(5,79,256,108), mode="Single", method="Default", keyword="将魂试炼", name="enter_ap100")
	# 继续点击屏幕 
	O_CONTINUE_CLICK = RuleOcr(roi=(544,672,195,43), area=(0,0,100,100), mode="Single", method="Default", keyword="点击屏幕继续", name="continue_click")
	# 剩余5倍次数 
	O_REMAIN_TIMESX5 = RuleOcr(roi=(746,29,64,23), area=(0,0,100,100), mode="DigitSmall", method="Default", keyword="", name="remain_timesx5")


