from module.atom.image import RuleImage
from module.atom.click import RuleClick
from module.atom.long_click import RuleLongClick
from module.atom.swipe import RuleSwipe
from module.atom.ocr import RuleOcr
from module.atom.list import RuleList

# This file was automatically generated by ./dev_tools/assets_extract.py.
# Don't modify it manually.
class MartialTrainingAssets: 


	# Click Rule Assets
	# 搜索锁定后左上角的第一个鬼王固定槽位 
	C_FIRST_BOSS_SLOT = RuleClick(roi_front=(120,105,120,70), roi_back=(120,105,120,70), name="first_boss_slot")


	# Image Rule Assets
	# 庭院活动入口 
	I_ACTIVITY_ENTRY = RuleImage(roi_front=(1195,465,27,33), roi_back=(1169,112,81,452), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_activity_entry.png")
	# 修行合训入口 
	I_TRAINING_ENTRY = RuleImage(roi_front=(1115,258,31,126), roi_back=(1101,209,56,217), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_training_entry.png")
	# 修行合训页面 
	I_TRAINING_PAGE = RuleImage(roi_front=(532,408,122,109), roi_back=(254,57,708,585), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_training_page.png")
	# 活动内庭院按钮 
	I_HOME_BUTTON = RuleImage(roi_front=(208,119,28,28), roi_back=(0,4,345,65), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_home_button.png")
	# 普通门票搜索按钮 
	I_SEARCH_NORMAL = RuleImage(roi_front=(1110,609,65,31), roi_back=(1104,603,77,43), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_search_normal.png")
	# 特殊门票搜索按钮 
	I_SEARCH_SPECIAL = RuleImage(roi_front=(1105,597,74,44), roi_back=(1098,590,88,58), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_search_special.png")
	# 门票类型切换按钮 
	I_TICKET_SWITCH = RuleImage(roi_front=(1167,540,23,24), roi_back=(1133,499,100,100), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_ticket_switch.png")
	# 普通门票模式标志 
	I_TICKET_NORMAL = RuleImage(roi_front=(1094,532,28,40), roi_back=(1056,522,100,56), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_ticket_normal.png")
	# 特殊门票模式标志 
	I_TICKET_SPECIAL = RuleImage(roi_front=(1095,533,24,39), roi_back=(1058,525,100,54), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_ticket_special.png")
	# 已有鬼王时的搜索锁定状态 
	I_SEARCH_LOCKED = RuleImage(roi_front=(1123,603,35,38), roi_back=(1070,575,137,110), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_search_locked.png")
	# 第一个鬼王入口 
	I_FIRST_BOSS = RuleImage(roi_front=(107,85,100,100), roi_back=(19,78,260,115), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_first_boss.png")
	# 第一个鬼王槽位为空 
	I_NO_BOSS = RuleImage(roi_front=(107,85,100,100), roi_back=(19,78,260,115), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_no_boss.png")
	# 鬼王挑战页面 
	I_BOSS_PAGE = RuleImage(roi_front=(553,69,171,44), roi_back=(480,42,331,85), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_boss_page.png")
	# 关闭鬼王挑战页面 
	I_BOSS_CLOSE = RuleImage(roi_front=(1182,67,44,50), roi_back=(1153,50,100,100), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_boss_close.png")
	# 挑战鬼王按钮 
	I_CHALLENGE = RuleImage(roi_front=(1106,536,75,75), roi_back=(1093,525,100,90), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_challenge.png")
	# 活动内式神录入口 
	I_RECORDS_ENTRY = RuleImage(roi_front=(1000,596,34,32), roi_back=(979,577,79,72), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_records_entry.png")
	# 阵容未锁定状态 
	I_TEAM_UNLOCKED = RuleImage(roi_front=(1100,454,23,26), roi_back=(1084,441,100,54), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_team_unlocked.png")
	# 阵容已锁定状态 
	I_TEAM_LOCKED = RuleImage(roi_front=(1101,455,21,27), roi_back=(1084,444,100,47), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/mt_team_locked.png")
	#  
	I_CONTINUE_CHALLENGE = RuleImage(roi_front=(1109,540,69,74), roi_back=(1093,526,100,100), threshold=0.8, method="Template matching", file="./tasks/MartialTraining/assets/assets_continue_challenge.png")


	# Ocr Rule Assets
	# 普通门票数量 
	O_NORMAL_TICKET_COUNT = RuleOcr(roi=(951,18,61,28), area=(948,15,66,33), mode="Single", method="Default", keyword="", name="normal_ticket_count")
	# 特殊门票数量 
	O_SPECIAL_TICKET_COUNT = RuleOcr(roi=(1149,20,67,24), area=(1143,16,77,31), mode="Single", method="Default", keyword="", name="special_ticket_count")
	# 鬼王名称 
	O_BOSS_NAME = RuleOcr(roi=(363,190,38,190), area=(363,190,38,190), mode="Single", method="Default", keyword="", name="boss_name")


